// Gallery - loads image data from generated gallery-data.js (galleryManifest variable)
// To add images: place them in the appropriate folder (img/rvp/<category>/)
// Then run: pwsh scripts/generate-gallery-manifest.ps1
// The manifest is also auto-generated by GitHub Actions on every push.

var galleryCategories = {
    "tesarske-prace": "Tesařské práce",
    "stavebni-prace": "Stavební práce",
    "fasadni-panely": "Fasádní panely",
    "pro-vase-projekty": "Pro Vaše projekty"
};

document.addEventListener("DOMContentLoaded", function () {
    var container = document.getElementById("rvp-gallery-container");
    var filtersContainer = document.getElementById("rvp-gallery-filters");
    if (!container || !filtersContainer) return;
    if (typeof galleryManifest === "undefined") return;

    var galleryData = galleryManifest;

    // Build filter buttons
    var allBtn = document.createElement("li");
    allBtn.className = "btn btn-outline-primary bg-white py-2 px-4 active mx-2 mb-4";
    allBtn.setAttribute("data-filter", "*");
    allBtn.innerHTML = '<h6 class="text-uppercase m-0">Vše</h6>';
    filtersContainer.appendChild(allBtn);

    Object.keys(galleryCategories).forEach(function (key) {
        if (!galleryData[key] || galleryData[key].length === 0) return;
        var btn = document.createElement("li");
        btn.className = "btn btn-outline-primary bg-white py-2 px-4 mx-2 mb-4";
        btn.setAttribute("data-filter", "." + key);
        btn.innerHTML = '<h6 class="text-uppercase m-0">' + galleryCategories[key] + '</h6>';
        filtersContainer.appendChild(btn);
    });

    // Hide container until images are loaded to prevent overlap
    container.style.opacity = "0";
    container.style.transition = "opacity 0.3s ease";

    // Build gallery items
    Object.keys(galleryCategories).forEach(function (key) {
        if (!galleryData[key]) return;
        galleryData[key].forEach(function (img) {
            var imgPath = "img/rvp/" + key + "/" + img;
            var col = document.createElement("div");
            col.className = "col-xl-4 col-lg-6 col-md-6 portfolio-item " + key;
            col.innerHTML =
                '<div class="position-relative portfolio-box">' +
                    '<img class="img-fluid w-100" src="' + imgPath + '" alt="' + galleryCategories[key] + '">' +
                    '<a class="portfolio-btn" href="' + imgPath + '" data-lightbox="portfolio">' +
                        '<i class="bi bi-plus text-white"></i>' +
                    '</a>' +
                '</div>';
            container.appendChild(col);
        });
    });

    // Initialize Isotope
    var portfolioIsotope = new Isotope(container, {
        itemSelector: ".portfolio-item",
        layoutMode: "fitRows"
    });

    // Re-layout once all images are loaded
    var images = container.querySelectorAll("img");
    var loadedCount = 0;
    var totalImages = images.length;

    function onImageLoad() {
        loadedCount++;
        if (loadedCount === totalImages) {
            portfolioIsotope.layout();
            container.style.opacity = "1";
        }
    }

    images.forEach(function (img) {
        if (img.complete) {
            onImageLoad();
        } else {
            img.addEventListener("load", onImageLoad);
            img.addEventListener("error", onImageLoad);
        }
    });

    // Filter click handlers
    filtersContainer.querySelectorAll("li").forEach(function (btn) {
        btn.addEventListener("click", function () {
            filtersContainer.querySelector(".active").classList.remove("active");
            this.classList.add("active");
            portfolioIsotope.arrange({ filter: this.getAttribute("data-filter") });
        });
    });
});
