// Auto-generated by scripts/generate-gallery-manifest.ps1 - DO NOT EDIT
var galleryManifest = {
  "tesarske-prace": [
    "drevostavba_vyhled.jpg",
    "pristresek_auto.jpg",
    "pristresek_drevo_venku.jpg",
    "pristresek_pes.jpg",
    "pristresek_vyhled.jpg",
    "zahradni_domek.jpg"
  ],
  "stavebni-prace": [
    "bourani_vnitrek.jpg",
    "dum_nekvalitni.jpg",
    "dum_nekvalitni2.jpg",
    "dum_venku_vyhled.jpg",
    "potrubi.jpg",
    "schody_betonovani.jpg",
    "splachovaci_system.jpg",
    "stavba_vyhled.jpg",
    "trubky.jpg"
  ],
  "fasadni-panely": [
    "zatepleni_stit.jpg"
  ],
  "pro-vase-projekty": [
    "dlazba_struska.jpg",
    "terasa_natercich.jpg"
  ]
};

