// Auto-generated by scripts/generate-gallery-manifest.ps1 - DO NOT EDIT
var galleryManifest = [
  "bourani_vnitrek.jpg",
  "dlazba_struska.jpg",
  "drevostavba_vyhled.jpg",
  "dum_nekvalitni.jpg",
  "dum_nekvalitni2.jpg",
  "dum_venku_vyhled.jpg",
  "potrubi.jpg",
  "pristresek_auto.jpg",
  "pristresek_drevo_venku.jpg",
  "pristresek_pes.jpg",
  "pristresek_vyhled.jpg",
  "schody_betonovani.jpg",
  "splachovaci_system.jpg",
  "stavba_vyhled.jpg",
  "terasa_natercich.jpg",
  "trubky.jpg",
  "zahradni_domek.jpg",
  "zatepleni_stit.jpg"
];

