// Gallery - loads image data from generated gallery-data.js (galleryManifest variable)
// To add images: place them in img/rvp/galerie/
// Then run: pwsh scripts/generate-gallery-manifest.ps1
// The manifest is also auto-generated by GitHub Actions on every push.

document.addEventListener("DOMContentLoaded", function () {
    var container = document.getElementById("rvp-gallery-container");
    if (!container) return;
    if (typeof galleryManifest === "undefined") return;

    // Hide container briefly to prevent initial overlap, show after first layout
    container.style.opacity = "0";
    container.style.transition = "opacity 0.3s ease";

    // Build gallery items
    galleryManifest.forEach(function (img) {
        var fullPath = "img/rvp/galerie/" + img;
        var thumbPath = "img/rvp/galerie/thumbs/" + img;
        var col = document.createElement("div");
        col.className = "col-xl-4 col-lg-6 col-md-6 portfolio-item";
        col.innerHTML =
            '<div class="position-relative portfolio-box">' +
                '<img class="img-fluid w-100" loading="lazy" src="' + thumbPath + '" alt="RVP realizace">' +
                '<a class="portfolio-btn" href="' + fullPath + '" data-lightbox="portfolio">' +
                    '<i class="bi bi-plus text-white"></i>' +
                '</a>' +
            '</div>';
        container.appendChild(col);
    });

    // Initialize Isotope
    var portfolioIsotope = new Isotope(container, {
        itemSelector: ".portfolio-item",
        layoutMode: "fitRows"
    });

    // Show gallery and re-layout as images load
    var revealed = false;
    function revealGallery() {
        if (!revealed) {
            revealed = true;
            portfolioIsotope.layout();
            container.style.opacity = "1";
        }
    }

    setTimeout(revealGallery, 500);

    container.addEventListener("load", function () {
        portfolioIsotope.layout();
    }, true);
});
