# Generate gallery-manifest.js from the folder structure in img/rvp/.
# Scans each category subfolder for image files and outputs a JS file with gallery data.
#
# Usage: pwsh scripts/generate-gallery-manifest.ps1

$galleryDir = Join-Path $PSScriptRoot ".." "img" "rvp"
$outputFile = Join-Path $PSScriptRoot ".." "js" "gallery-data.js"
$imageExtensions = @(".jpg", ".jpeg", ".png", ".gif", ".webp", ".avif")

$categories = @(
    "tesarske-prace",
    "stavebni-prace",
    "fasadni-panely",
    "pro-vase-projekty"
)

$manifest = [ordered]@{}
$total = 0

foreach ($category in $categories) {
    $categoryPath = Join-Path $galleryDir $category
    if (Test-Path $categoryPath) {
        $images = Get-ChildItem -Path $categoryPath -File |
            Where-Object { $imageExtensions -contains $_.Extension.ToLower() } |
            Sort-Object Name |
            Select-Object -ExpandProperty Name
        if ($null -eq $images) { $images = @() }
        if ($images -is [string]) { $images = @($images) }
        $manifest[$category] = $images
        $total += $images.Count
    } else {
        $manifest[$category] = @()
    }
}

$json = $manifest | ConvertTo-Json -Depth 3
$jsContent = "// Auto-generated by scripts/generate-gallery-manifest.ps1 - DO NOT EDIT`nvar galleryManifest = $json;`n"
Set-Content -Path $outputFile -Value $jsContent -Encoding UTF8

Write-Host "Generated $outputFile with $total images across $($categories.Count) categories."
