# Generate gallery-manifest.js from images in img/rvp/galerie/.
# Scans the gallery folder for image files and outputs a JS file with a flat array.
#
# Usage: pwsh scripts/generate-gallery-manifest.ps1

$galleryDir = Join-Path $PSScriptRoot ".." "img" "rvp" "galerie"
$outputFile = Join-Path $PSScriptRoot ".." "js" "gallery-data.js"
$imageExtensions = @(".jpg", ".jpeg", ".png", ".gif", ".webp", ".avif")

$images = @()
if (Test-Path $galleryDir) {
    $images = Get-ChildItem -Path $galleryDir -File |
        Where-Object { $imageExtensions -contains $_.Extension.ToLower() } |
        Sort-Object Name |
        Select-Object -ExpandProperty Name
    if ($null -eq $images) { $images = @() }
    if ($images -is [string]) { $images = @($images) }
}

$json = $images | ConvertTo-Json -Depth 1
$jsContent = "// Auto-generated by scripts/generate-gallery-manifest.ps1 - DO NOT EDIT`nvar galleryManifest = $json;`n"
Set-Content -Path $outputFile -Value $jsContent -Encoding UTF8

Write-Host "Generated $outputFile with $($images.Count) images."
